ekf_local:
  ros__parameters:
    # Local EKF (e.g., ekf_local.yaml)
    frequency: 30.0              # High update rate for control
    world_frame: odom          # Output odom->base_link
    two_d_mode: false

    # Whether to publish the acceleration state. Defaults to false if unspecified.
    publish_acceleration: true

# Whether to broadcast the transformation over the /tf topic. Defaults to true if unspecified.
    publish_tf: true


    imu0: imu1/data            # First IMU (orientation/angular velocity)
    imu0_config: [false, false, false,
                  false, false, false,
                  false, false, false,
                  false, true, true,
                  false, false, false] # TODO tune based on what sensor reads
    imu0_differential: true

    imu1: imu2/data            # Second IMU (redundancy/fault tolerance)
    imu1_config: [false, false, false,
                  false, false, false,
                  false, false, false,
                  false, true, true,
                  false, false, false] #TODO tune based on what sensor reads
    imu1_differential: true

    odom0: wheel_encoder/odom  # Wheel encoder odometry
    odom0_config: [false, false, false,
                  false, false, false,
                  true, true, false,
                  false, false, true,
                  false, false, false] #TODO tune based on what sensor reads
    odom0_differential: true





