local_costmap:
  local_costmap:
    ros__parameters:
      update_frequency: 5.0
      publish_frequency: 2.0
      global_frame: odom
      robot_base_frame: base_link
      use_sim_time: True
      rolling_window: true
      width: 20 
      height: 20
      origin_x: -5.0
      origin_y: -5.0
      resolution: 0.05
      footprint: "[ [0.21, 0.195], [0.21, -0.195], [-0.21, -0.195], [-0.21, 0.195] ]"
      plugins: ["obstacle_layer", "lines_layer", "inflation_layer"]
      lines_layer:
        plugin: "line_layer::LineLayer"
        enabled: True
        line_topic: "/line_points"
      inflation_layer:
        plugin: "nav2_costmap_2d::InflationLayer"
        cost_scaling_factor: 3.0
        inflation_radius: 0.55
      obstacle_layer:
        plugin: "nav2_costmap_2d::ObstacleLayer"
        enabled: True
        observation_sources: pointcloud
        pointcloud:
          topic: /depth_camera/points
          data_type: "PointCloud2"
      static_layer:
        map_subscribe_transient_local: True
      always_send_full_costmap: True
  local_costmap_client:
    ros__parameters:
      use_sim_time: True
  local_costmap_rclcpp_node:
    ros__parameters:
      use_sim_time: True

global_costmap:
  global_costmap:
    ros__parameters:
      update_frequency: 1.0
      publish_frequency: 1.0
      global_frame: map
      robot_base_frame: base_link
      use_sim_time: True
      robot_radius: 0.3
      resolution: 0.05
      track_unknown_space: true
      plugins: ["static_layer", "obstacle_layer",   "inflation_layer" ]
      #line_layer:
      #  plugin: "line_layer::LineLayer"
      #  enabled: True
      obstacle_layer:
        plugin: "nav2_costmap_2d::ObstacleLayer"
        enabled: True
        observation_sources: pointcloud 
        pointcloud:
          topic: /depth_camera/points
          data_type: "PointCloud2"
      static_layer:
        plugin: "nav2_costmap_2d::StaticLayer"
        map_subscribe_transient_local: True
      inflation_layer:
        plugin: "nav2_costmap_2d::InflationLayer"
        cost_scaling_factor: 3.0
        inflation_radius: 0.55
      always_send_full_costmap: True
  global_costmap_client:
    ros__parameters:
      use_sim_time: True
  global_costmap_rclcpp_node:
    ros__parameters:
      use_sim_time: True

  
controller_server:
  ros__parameters:
    controller_plugins: ["FollowPath"]
    FollowPath:
      plugin: "dwb_core::DWBLocalPlanner"
      max_vel_x: 0.5          # Max forward speed (m/s)
      min_vel_x: 0.1          # Min forward speed (m/s)
      path_distance_bias: 32.0 # Stay on path vs avoid obstacles
      goal_distance_bias: 20.0
      costmap_weight_obstacle: 0.8
      critics: ["ObstacleFootprint", "GoalAlign", "PathAlign", "PathDist", "GoalDist"]
      ObstacleFootprint:
        scale: 1.0
      GoalAlign:
        scale: 24.0
      PathAlign:
        scale: 32.0
      PathDist:
        scale: 32.0
      GoalDist:
        scale: 24.0


behavior_server:
  ros__parameters:
    local_costmap_topic: "local_costmap/costmap_raw"
    global_costmap_topic: "global_costmap/costmap_raw"
    local_footprint_topic: "local_costmap/published_footprint"
    global_footprint_topic: "global_costmap/published_footprint"
    cycle_frequency: 10.0
    action_server_result_timeout: 10.0  # seconds (sometimes 900.0 in older releases)
    behavior_plugins: ["spin", "backup", "drive_on_heading", "wait"]
    spin:
      plugin: "nav2_behaviors/Spin"
    backup:
      plugin: "nav2_behaviors/BackUp"
    drive_on_heading:
      plugin: "nav2_behaviors/DriveOnHeading"
    wait:
      plugin: "nav2_behaviors/Wait"