
local_costmap:
  local_costmap:
    ros__parameters:
      update_frequency: 5.0
      publish_frequency: 2.0
      global_frame: odom
      robot_base_frame: base_link
      use_sim_time: True
      rolling_window: true
      transform_tolerance: 0.5
      width: 9
      height: 9
      resolution: 0.05
      robot_radius: 0.22
      plugins: ["voxel_layer",  "inflation_layer"]
      lines_layer:
        plugin: "line_layer::LineLayer"
        enabled: True
        line_topic: "/line_points"
        
      inflation_layer:
        plugin: "nav2_costmap_2d::InflationLayer"
        cost_scaling_factor: 3.0
        inflation_radius: 0.55
      voxel_layer:
        plugin: "nav2_costmap_2d::VoxelLayer"
        enabled: True
        publish_voxel_map: True
        origin_z: 0.0
        z_resolution: 0.05
        z_voxels: 16
        max_obstacle_height: 2.0
        mark_threshold: 0
        observation_sources: scan
        scan:
          topic: /scan
          max_obstacle_height: 2.0
          clearing: True
          marking: True
          data_type: "LaserScan"
          raytrace_max_range: 3.0
          raytrace_min_range: 0.0
          obstacle_max_range: 2.5
          obstacle_min_range: 0.0
      static_layer:
        plugin: "nav2_costmap_2d::StaticLayer"
        map_subscribe_transient_local: True
      always_send_full_costmap: True


controller_server:
  ros__parameters:
    use_sim_time: True
    goal_checker_plugin: "simple_goal_checker"
    goal_checker:
      plugin: "nav2_controller::SimpleGoalChecker"
      xy_goal_tolerance: 0.25
    controller_plugins: ["FollowPath"]
    global_frame: odom
    FollowPath:
      plugin: "dwb_core::DWBLocalPlanner"
      #min_vel_x: 0.0  # Disable backward motion
      #max_vel_x: 0.26
      #min_vel_y: 0.0
      #max_vel_y: 0.0
      critics: ["PathAlign", "GoalAlign", "ObstacleFootprint", "Oscillation"]

bt_navigator:
  ros__parameters:
    use_sim_time: True
    default_nav_to_pose_bt_xml: "/home/vtcro/AutoNav/isaac_ros-dev/install/slam/share/slam/behavior_trees/bt_2.xml"
    default_nav_through_poses_bt_xml: "/home/vtcro/AutoNav/isaac_ros-dev/install/slam/share/slam/behavior_trees/bt_2.xml"
    plugin_lib_names:
      - nav2_is_path_valid_condition_bt_node
      - nav2_navigate_to_pose_action_bt_node

      - nav2_follow_path_action_bt_node
      - nav2_goal_updated_condition_bt_node
      - nav2_initial_pose_received_condition_bt_node
      - nav2_pipeline_sequence_bt_node

    