control_node:
  ros__parameters:
    # \/ ------------------configure serial ports here 
    motor_port: "/dev/ttyACM0"
    arduino_port: "/dev/ttyACM1"
    gps_port: "/dev/ttyTCU0"
    # \/ ------------------configure topic names here
    controller_topic: "joy"
    encoder_topic: "encoders"
    gps_topic: "gps"
    path_planning_topic: "cmd_vel"
