control_node:
  ros__parameters:
    # \/ ------------------configure serial ports here 

    motor_port: "/dev/ttyACM0"
    arduino_port: "/dev/ttyACM1"

    # \/ ------------------configure topic names here
    controller_topic: "joy"
    encoder_topic: "encoders"
    path_planning_topic: "cmd_vel"
