# Start with the ISAAC ROS base image

arg BASE_IMAGE
FROM ${BASE_IMAGE}

# Install dependencies for ZED SDK and tmux
RUN apt-get update && \
    apt-get install -y wget build-essential tmux && \
    apt-get clean && \
    rm -rf /var/lib/apt/lists/*

# Download and install the ZED SDK
RUN wget -q --show-progress --progress=bar:force:noscroll -O ZED_SDK.run "https://download.stereolabs.com/zedsdk/3.5/jp45/jetsons" && \
    chmod +x ZED_SDK.run && \
    ./ZED_SDK.run --quiet --noexec --target /usr/local/zed

# Set environment variables for ZED SDK
ENV ZED_SDK_ROOT=/usr/local/zed
ENV LD_LIBRARY_PATH=$LD_LIBRARY_PATH:/usr/local/zed/lib

# Define the default command to run when the container starts
CMD ["bash"]

