<?xml version="1.0"?>
<robot xmlns:xacro="http://www.ros.org/wiki/xacro" >



    <xacro:property name="base_width" value="0.31"/>
    <xacro:property name="base_length" value="0.42"/>
    <xacro:property name="base_height" value="0.18"/>



    <xacro:include filename="inertial_macros.xacro"/>
    <xacro:property name="wheel_radius" value="0.10"/>
    <xacro:property name="wheel_width" value="0.04"/>
    <xacro:property name="wheel_ygap" value="0.025"/>
    <xacro:property name="wheel_zoff" value="0.05"/>
    <xacro:property name="wheel_xoff" value="0.12"/>





    <material name="white">
        <color rgba="1 1 1 1"/>
    </material>

    <material name="orange">
        <color rgba="1 0.3 0.1 1"/>
    </material>

    <material name="blue">
        <color rgba="0.2 0.2 1 1"/>
    </material>

    <material name="black">
        <color rgba="0 0 0 1"/>
    </material>

    <material name="red">
        <color rgba="1 0 0 1"/>
    </material>

    <!--START OF BASE LINK-->
    <link name="base_link">
    </link>
    <!--END OF BASE LINK-->

    <!-- Robot Footprint -->
    <link name="base_footprint"/>

    <joint name="base_joint" type="fixed">
        <parent link="base_link"/>
        <child link="base_footprint"/>
        <origin xyz="0.0 0.0 ${-(wheel_radius+wheel_zoff)}" rpy="0 0 0"/>
    </joint>




    <!--START OF CHASSIS LINK-->
    <joint name="chassis_joint" type="fixed">
        <parent link="base_link"/>
        <child link="chassis"/>
        <origin xyz="0 0 0"/>
    </joint>

    <!--START OF CHASSIS MODEL-->
    <link name="chassis">
        <visual>
            <origin xyz="0 0 0" rpy="0 0 0"/>
            <geometry>
                <mesh 
			filename="file://$(find autonav_sim)/custom_models/baseframe.STL"
                    scale="0.001 0.001 0.001"/>
            </geometry>
            <material name="white"/>
        </visual>
        <collision>
            <origin xyz="0 0 0" rpy="0 0 0"/>
            <geometry>
                <mesh
			filename="file://$(find autonav_sim)/custom_models/baseframe.STL"
                    scale="0.001 0.001 0.001"/>
            </geometry>
        </collision>
        <xacro:inertial_box mass="0.5" x="0.8636" y="0.4572" z="0.41021">
            <origin xyz="0 0 0" rpy="0 0 0"/>
        </xacro:inertial_box>
        
    </link>

    <gazebo reference="chassis">
        <material>Gazebo/Grey</material>
    </gazebo>
    <!--END OF CHASSIS MODEL-->
    <!--END OF CHASSIS LINK-->

    <!--START OF LEFT Wros2 lauros2 launch autonav_sim launch_sim.launch.py world:=./src/autonav_sim/worlds/autonav_igvc_course.worldnch autonav_sim launch_sim.launch.py world:=./src/autonav_sim/worlds/autonav_igvc_course.worldHEEL LINK-->
    <joint name="left_wheel_joint" type="continuous">
        <parent link="base_link"/>
        <child link="left_wheel"/>
        <origin xyz="0 0.2686 -0.04318" rpy="-${pi/2} 0 0"/>
        <axis xyz="0 0 1"/>
    </joint>

    <!--START OF LEFT WHEEL MODEL-->
    <link name="left_wheel">
        <visual>
            <geometry>
                <cylinder radius="0.2" length="0.08"/>
            </geometry>
            <material name="blue"/>
        </visual>
        <collision>
            <geometry>
                <cylinder radius="0.2" length="0.08"/>
            </geometry>
        </collision>
        <xacro:inertial_cylinder mass="0.1" length="0.08" radius="0.2">
            <origin xyz="0 0 0" rpy="0 0 0"/>
        </xacro:inertial_cylinder>
    </link>

    <gazebo reference="left_wheel">
        <material>Gazebo/Blue</material>
    </gazebo>
    <!--END OF LEFT WHEEL MODEL-->
    <!--END OF LEFT WHEEL LINK-->

    <!--START OF RIGHT WHEEL LINK-->
    <joint name="right_wheel_joint" type="continuous">
        <parent link="base_link"/>
        <child link="right_wheel"/>
        <origin xyz="0 -0.2686 -0.04318" rpy="${pi/2} 0 0"/>
        <axis xyz="0 0 -1"/>
    </joint>

    <!--START OF RIGHT WHEEL MODEL-->
    <link name="right_wheel">
        <visual>
            <geometry>
                <cylinder radius="0.2" length="0.08"/>
            </geometry>
            <material name="blue"/>
        </visual>
        <collision>
            <geometry>
                <cylinder radius="0.2" length="0.08"/>
            </geometry>
        </collision>
        <xacro:inertial_cylinder mass="0.1" length="0.08" radius="0.2">
            <origin xyz="0 0 0" rpy="0 0 0"/>
        </xacro:inertial_cylinder>
    </link>

    <gazebo reference="right_wheel">
        <material>Gazebo/Blue</material>
    </gazebo>
    <!--END OF RIGHT WHEEL MODEL-->
    <!--END OF RIGHT WHEEL LINK-->

    <!--START OF FRONT CASTER WHEEL LINK-->
    <joint name="frontcaster_wheel_joint" type="fixed">
        <parent link="chassis"/>
        <child link="frontcaster_wheel"/>
        <origin xyz="0.39116 0 -0.15113" rpy="0 0 0"/>
    </joint>

    <!--START OF FRONT CASTER WHEEL MODEL-->
    <link name="frontcaster_wheel">
        <visual>
            <geometry>
                <sphere radius="0.09205" />
            </geometry>
            <material name="black"/>
        </visual>
        <collision>
            <geometry>
                <sphere radius="0.09205" />
            </geometry>
        </collision>
        <xacro:inertial_sphere mass="0.1" radius="0.09205">
            <origin xyz="0 0 0" rpy="0 0 0"/>
        </xacro:inertial_sphere>
    </link>

    <gazebo reference="frontcaster_wheel">
        <material>Gazebo/Black</material>
        <mu1 value="0.001"/>
        <mu2 value="0.001"/>
    </gazebo>
    <!--END OF FRONT CASTER WHEEL MODEL-->
    <!--END OF FRONT CASTER WHEEL LINK-->

    <!--START OF BACK CASTER WHEEL LINK-->
    <joint name="backcaster_wheel_joint" type="fixed">
        <parent link="chassis"/>
        <child link="backcaster_wheel"/>
        <origin xyz="-0.39116 0 -0.15113" rpy="0 0 0"/>
    </joint>

    <!--START OF BACK CASTER WHEEL MODEL-->
    <link name="backcaster_wheel">
        <visual>
            <geometry>
                <sphere radius="0.09205" />
            </geometry>
            <material name="black"/>
        </visual>
        <collision>
            <geometry>
                <sphere radius="0.09205" />
            </geometry>
        </collision>
        <xacro:inertial_sphere mass="0.1" radius="0.09205">
            <origin xyz="0 0 0" rpy="0 0 0"/>
        </xacro:inertial_sphere>
    </link>

    <gazebo reference="backcaster_wheel">
        <material>Gazebo/Black</material>
        <mu1 value="0.001"/>
        <mu2 value="0.001"/>
    </gazebo>
    <!--END OF BACK CASTER WHEEL MODEL-->
    <!--END OF BACK CASTER WHEEL LINK-->
        


</robot>
